GallonShih/twitter-api-2020

migrations/20190115071420-create-reply.js, migrations/20190115071420-create-tweet.js, migrations/20190115071421-create-user.js, models/followship.js, models/like.js, models/reply.js, models/tweet.js, models/user.js
[WHAT]
調整 models 與 migration 以符合 test檔案
[DETAIL]
1. 補齊 models 的 id, createdAt, updatedAt
2. 調整 migrations 的Datatype 以符合 test
3. 放寬寫進DB 的VARCHAR長度
4. 建立 Like 的 associate
=> Adjust models & migrations

config/passport.js, controllers/user-controller.js, middleware/auth.js, routes/index.js, routes/modules/admin.js, routes/modules/users.js
[WHAT]
add getUser controller
[DETAIL]
-fix middleware/auth.js
- fix jwt authenticated
- fix authenticatedAdmin
- fix authenticatedUser
- add getUser controller
=> feat: add getUser api

controllers/tweet-controller.js, helpers/pagination-helper.js, routes/modules/tweets.js
[WHAT]
開發第一版Tweets相關 API
[DETAIL]
1. GET /api/tweets
2. POST /api/tweets
3. GET /api/tweets/:id
4. GET /api/tweets/:id/replies
5. POST /api/tweets/:id/replies
=> Tweets相關 API

Procfile, config/config.json
[WHAT]
設置佈署於Heroku相關文件
[DETAIL]
1. 修改 production 下的 mysql 連線參數
2. 建立 Heroku 設定檔 Procfile
=> Heroku Setting

controllers/reply-controller.js, middleware/auth.js, migrations/20190115071421-create-user.js, models/user.js, routes/modules/replies.js
[WHAT]
建立 likeReply & unlikeReply API
[DETAIL]
1. 建立 likeReply & unlikeReply API
2. User model 的 role 設置 defaultValue user
3. 在 middleware 的 auth 中，取得user.dataValues
=> Reply like related

package-lock.json
=> fix: package-log

controllers/followship-controller.js, controllers/user-controller.js, package-lock.json, package.json, routes/modules/followships.js
[WHAT]
create followship APIs
[DETAIL]
create addFollowing controller
create removeFollowing controller
change usercontroller naming: confirmPassword => checkPassword
fix puUser controller
install cors locally
=> Create followship apis

swagger-output.json
[WHAT]
加入 heroku 版本的 host，以及調整預設文字
=> Fix swagger

controllers/admin-controller.js, controllers/user-controller.js, routes/index.js, routes/modules/admin.js
[WHAT]
admin apis
[DETAIL]
add signIn controller
add getUsers controller
add deleteTweet controller
create currentUser controller
edit upper case
=> Create admin apis

controllers/tweet-controller.js, swagger-output.json
[WHAT]
調整 getTweet，以及修改Swagger 設定
=> Adjust tweet controller

controllers/followship-controller.js, controllers/user-controller.js, middleware/auth.js, routes/index.js, swagger-output.json, test/requests/admin.spec.js, test/requests/user.spec.js
[WHAT]
調整檔案以完成測試，並調整swagger
[DETAIL]
1. 使用 getUser
2. 調整 followshih controller
3. 調整路由順序
4. 新增api 至 swagger
=> Fix test error & adjust swagger

controllers/user-controller.js, middleware/auth.js
[DETAIL]
fix user api
[WHAT]
- fix: adjust auth to fit test file, fix image upload
- delete get current user password
- edit putUser null response
=> Fix test requests

controllers/user-controller.js, helpers/file-helpers.js
[WHAT]
fix putUser api
[DETAIL]
- fix pawword
- fix image upload
=> Fix put user api

controllers/user-controller.js
[WHAT]
adjust user api
[DETAIL]
getTweets: add isLiked
=> feat: add isLiked

controllers/admin-controller.js, routes/modules/admin.js
[WAHT]
admin api
[DETAIL]
add getTweets
=> feat: add getTweets

controllers/user-controller.js
[WHAT]
fix user api
[DETAIL]
- fix getLikes account doesn't exist
- add getReplies user name
=> Fix get likes

controllers/user-controller.js
[WHAT]
修正 putUser 錯誤
[DETAIL]
1. update 時，如果avatar或 cover是null ，則使用db 原本的資料
2. 事先檢查 req.body 或 req.file是否存在
=> Fix put user

middleware/error-handler.js, swagger-output.json
=> 調整Error格式與Swagger

config/passport.js, controllers/user-controller.js
[WAHT]
add tweetCount
[DETAIL]
psssport config
getCurrentUser controller
=> add tweet count

controllers/user-controller.js
=> fix: put-user

controllers/user-controller.js
[WHAT]
fix user apis
[DETAIL]
getLikes
=> Fix user api

controllers/user-controller.js
[WHAT]
fix getTopUsers
[DETAIL]
remove user himself/herself from top10
=> fix: remove oneself from top10

.travis.yml
=> adjust: add env variable in travis.yml
